KILOBYTE = 1024
MEGABYTE = 1024 * KILOBYTE
MAX_FILE_SIZE = 16 * MEGABYTE
SUPPORTED_FILE_MAGIC = {b"MZ"}
DEFAULT_MIN_LENGTH = 4
MAX_STRING_LENGTH = 2048
DS_FUNCTION_CTX_THRESHOLD = 15
DS_FUNCTION_MIN_DECODED_STRINGS = 5
