import { execSync } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const repo = join(root, '..');

// track the FLOSS release version so the viewer never needs its own manual bumps
const versionPy = readFileSync(join(repo, 'floss', 'version.py'), 'utf8');
const flossVersion = versionPy.match(/^__version__\s*=\s*['"]([^'"]+)['"]/m)?.[1];
if (!flossVersion) {
  throw new Error('could not parse __version__ from floss/version.py');
}

let commit = 'unknown';
let date = 'unknown';
try {
  commit = execSync('git rev-parse --short HEAD', { cwd: repo }).toString().trim();
  date = execSync('git log -1 --format=%cd --date=format:%y-%m-%d', { cwd: repo }).toString().trim();
} catch {
  // not a git checkout (e.g. release tarball); fall back to 'unknown'
}

const out = `// Generated by scripts/generate-version.mjs — do not edit.
export const VIEWER_VERSION = '${flossVersion}';
export const VIEWER_COMMIT = '${commit}';
export const VIEWER_DATE = '${date}';
`;

const dest = join(root, 'src', 'generated', 'version.ts');
mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, out);
console.log(`generated version.ts (v${flossVersion}, commit ${commit}, ${date})`);
