[mypy]
plugins = pydantic.mypy
mypy_path = .

[mypy-viv_utils.*]
ignore_missing_imports = True

[mypy-flirt.*]
ignore_missing_imports = True

[mypy-vivisect.*]
ignore_missing_imports = True

[mypy-envi.*]
ignore_missing_imports = True

[mypy-PE.*]
ignore_missing_imports = True

[mypy-pytest.*]
ignore_missing_imports = True

[mypy-idc.*]
ignore_missing_imports = True

[mypy-tqdm.*]
ignore_missing_imports = True

[mypy-networkx.*]
ignore_missing_imports = True

[mypy-halo.*]
ignore_missing_imports = True

[mypy-pefile.*]
ignore_missing_imports = True

[mypy-intervaltree.*]
ignore_missing_imports = True

[mypy-lancelot.*]
ignore_missing_imports = True

[mypy-capa.*]
ignore_missing_imports = True

[mypy-virustotal3.*]
ignore_missing_imports = True

[mypy-colorama.*]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True

[mypy-bs4.*]
ignore_missing_imports = True
[mypy-binary2strings.*]
ignore_missing_imports = True
